name: Leak Tests

on:
    - push
    - fork
    - pull_request

jobs:
    tests:
        runs-on: ubuntu-latest
        name: "Running unit tests for PHP ${{ matrix.php-version }}"
        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.0', '8.1']
        steps:
            - uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2
            - run: composer install
              shell: bash
            - run: composer test:leak
              shell: bash
