name: YML lint

on:
    - push
    - fork
    - pull_request

jobs:
    yml-lint:
        runs-on: ubuntu-latest
        name: "YML lint"
        steps:
            - uses: actions/checkout@v2
            - run: docker pull cytopia/yamllint
            - run: docker run --rm -t -v $(pwd):/data cytopia/yamllint .
              shell: bash
